CREATE TABLE BITACORA (
BITA_ID SERIAL NOT NULL,
BITA_FECHA DATE,
BITA_MALWARE INT NOT NULL,
BITA_PISHING INT NOT NULL,
BITA_COMAN_CONT INT NOT NULL,
BITA_CRYPTOMINERIA INT NOT NULL,
BITA_DDOS INT NOT NULL,
BITA_CONEX_BLOQ INT NOT NULL,
BITA_TOTAL INT NOT NULL,
BITA_SITUACION SMALLINT DEFAULT 1,
PRIMARY KEY (BITA_ID)
);

